__all__ = [
    'IP_HEADER_SIZE',
    'UDP_HEADER_SIZE',
    'PACKET_HEADER_SIZE',
    'RAKNET_WEIRD'
]


IP_HEADER_SIZE = 20
UDP_HEADER_SIZE = 8
PACKET_HEADER_SIZE = IP_HEADER_SIZE + UDP_HEADER_SIZE
RAKNET_WEIRD = 8
